### ISSUE TITLE
Error using single .gct file

### ISSUE THREAD

**Issue by shwetajohari** [broadinstitute/ssGSEA2.0#12]
Running ssSGEA on: FFPEAGCTfinal.gct 

parsing as GCT v1.2
C:\Users\pc\Desktop\2nd try 17oct2019/FFPEAGCTfinal.gct 15859 rows, 1 cols, 0 row descriptors, 0 col descriptors
parsing as GCT v1.2
C:\Users\pc\Desktop\2nd try 17oct2019/FFPEAGCTfinal_unique.gct 15859 rows, 1 cols, 0 row descriptors, 0 col descriptors
Error in ssGSEA2(input.ds, gene.set.databases = gene.set.databases, sample.norm.type = sample.norm.type,  : 
  No overlap to any gene sets found in your data set!
Possible reasons: 1) organism other than human; 2) wrong format of gene names/site ids!
In addition: Warning message:
In ssGSEA2(input.ds, gene.set.databases = gene.set.databases, sample.norm.type = sample.norm.type,  :
 
 Error in ssGSEA2(input.ds, gene.set.databases = gene.set.databases, sample.norm.type = sample.norm.type,  : 
  No overlap to any gene sets found in your data set!
Possible reasons: 1) organism other than human; 2) wrong format of gene names/site ids!

**Comment by shwetajohari** [comment]
The .gct and .gmt files are uploaded for your reference. 
These are for mouse.
[2nd try 17oct2019.zip](https://github.com/broadinstitute/ssGSEA2.0/files/3739806/2nd.try.17oct2019.zip)

**Comment by karstenkrug** [comment]
The error message which you posted above should point you into the right direction:

"No overlap to any gene sets found in your data set!
Possible reasons: 1) organism other than human; 2) wrong format of gene names/site ids!"

I briefly checked your files and it seems like the GCT files contains either mouse or rat gene symbols while the GMT files contains human gene symbols. You either have to convert mouse gene symbols to human or use mouse-specific gene sets.

**Comment by shwetajohari** [comment]
Respected, 
Thank you for letting me know, however, changing the gene set and redoing it, error is still persisting

parsing as GCT v1.3
C:\Users\pc\Desktop\shweta\attempt1/FFPEAGCTfinal.gct 15859 rows, 1 cols, NA row descriptors, NA col descriptors
Error in ssGSEA2(input.ds, gene.set.databases = gene.set.databases, sample.norm.type = sample.norm.type,  : 
  

Error importing GCT file using 'cmapR::parse.gctx()'. The GCT file doesn't seem to be in the correct format!
Please see take a look at https://clue.io/connectopedia/gct_format for details about GCT format.

Error message thrown by 'cmapR::parse.gctx()':

In addition: Warning message:
In FUN(X[[i]], ...) :
 
 Error in ssGSEA2(input.ds, gene.set.databases = gene.set.databases, sample.norm.type = sample.norm.type,  : 
  

Error importing GCT file using 'cmapR::parse.gctx()'. The GCT file doesn't seem to be in the correct format!
Please see take a look at https://clue.io/connectopedia/gct_format for details about GCT format.

Error message thrown by 'cmapR::parse.gctx()': 
[attempt1.zip](https://github.com/broadinstitute/ssGSEA2.0/files/3739885/attempt1.zip)

**Comment by karstenkrug** [comment]
Again, the error message should point  you to a problem with your GCT file, not the database. 

"The GCT file doesn't seem to be in the correct format!"

This is the file you are trying to use now which is not going to work because header and number of data columns do not match.

![image](https://user-images.githubusercontent.com/15931402/67021876-50245b80-f0ce-11e9-8256-b6ec5907188f.png)

This is the file which you have used previously and which is correctly formatted:

![image](https://user-images.githubusercontent.com/15931402/67021632-ec019780-f0cd-11e9-9785-ba49c6301f57.png)

In addition I noticed that you are still using human gene symbols in your GMT file.
