### ISSUE TITLE
can not run example gct file PI3K_pert_logP_n2x23936.gct

### ISSUE THREAD

**Issue by jzsbioinfo** [broadinstitute/ssGSEA2.0#14]
Error in ssGSEA2(input.ds, gene.set.databases = gene.set.databases, sample.norm.type = sample.norm.type,  : 
  

Error importing GCT file using 'cmapR::parse.gctx()'. The GCT file doesn't seem to be in the correct format!
Please see take a look at https://clue.io/connectopedia/gct_format for details about GCT format.

Error message thrown by 'cmapR::parse.gctx()':

I work on windows10, R version 3.6.2 and once I git-clone the ssGSEA2.0, I follow the instruction choose the example gct file and choose gmt file n the db folder. I have tried so many times, it doesn't work.
Hope somebody can help me, thanks!

**Comment by karstenkrug** [comment]
It seem like a more general problem since I got several messages describing the same issue. However, I just ran the example and it worked fine on my local machine (Win 10, R 3.6.1). So we'll have to figure out what's causing the problem. 

Let's start with two scenarios:

**1) the GCT file is not in the correct format.**
* Please make sure to download the file in RAW format.
* Don't save a GCT from Excel since it will mess up the format of the two header lines.

**2) The cmapR package did not install correctly.**
* Could you please try to import the GCT file manually? This will give some more detailed error message.

`library("cmapR")`
`gct <- parse.gctx("/path/to/PI3K_pert_logP_n2x23936.gct")` 

It would be great if you could check the points above and report back.

Thanks,
K

**Comment by jzsbioinfo** [comment]
I think I find the solution. Thanks for your remind of "cmapR" package, I notice in cmapR, there is only cmapR::parse_gctx, but not cmapR::parse.gctx. So, to use the ssgsea-gui.R, you will need to replace all parse.gctx with parse_gctx   and  replace all write.gct with write_gct in ssgsea-gui.R and src/ssGSEA2.0.R. Then I can successfully run it.

**Comment by jzsbioinfo** [comment]
Thanks for your suggsetions, I have solved the problem. If you do not mind, I have a question.


In the&nbsp;Barbie et al. 2009 paper, according to the formular:

Now, suppose we have 3 genes A,B and C, the rank is 1,2 and 3. When we calculate PWG(G,S,2) use the above formular (here let's set α=1),&nbsp;
it is 1/(1+2+3) + 2/(1+2+3).


We will see the contribution of gene A to the&nbsp;PWG(G,S,2), 1/(1+2+3) is even smaller than the contribution of gene B to the PWG(G,S,2) which is 2/(1+2+3).


This what I feel confused, because I will think gene A has higher expression, which shall give higher weight. I would think replace the gene expression with the reverse of rank use rather than rank will make more sense.


Hope you can understand my question, it will be great if you know the answer.



Thanks
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Karsten Krug"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月5日(星期三) 凌晨0:28
收件人:&nbsp;"broadinstitute/ssGSEA2.0"<ssGSEA2.0@noreply.github.com&gt;;
抄送:&nbsp;"建造师"<1779408152@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [broadinstitute/ssGSEA2.0] can not run example gct file PI3K_pert_logP_n2x23936.gct (#14)




It seem like a more general problem since I got several messages describing the same issue. However, I just ran the example and it worked fine on my local machine (Win 10, R 3.6.1). So we'll have to figure out what's causing the problem.
 
Let's start with two scenarios:
 
1) the GCT file is not in the correct format.
  
Please make sure to download the file in RAW format.
 
Don't save a GCT from Excel since it will mess up the format of the two header lines.
  
2) The cmapR package did not install correctly.
  
Could you please try to import the GCT file manually? This will give some more detailed error message.
  
library("cmapR")
 gct <- parse.gctx("/path/to/PI3K_pert_logP_n2x23936.gct")
 
It would be great if you could check the points above and report back.
 
Thanks,
 K

**Comment by karstenkrug** [comment]
Sorry for my slow response here...

Thanks for looking into that! While the problem you encountered had been [addressed by the cmapR folks](https://github.com/cmap/cmapR/commit/6a255d00b22e1d53d8e742b2a33cd1790281c1a3), it seems like the ```cmapR``` package currently has some issues. I pushed a bugfix 20 days ago which does not require the ```cmapR``` package to be installed on your machine but uses the ```io.R``` script from the package instead.

I think this will be a temporary fix though and I will use the ```cmapR``` package again once it will become available through Bioconductor.
