### ISSUE TITLE
Constant Error

### ISSUE THREAD

**Issue by erikfel97** [broadinstitute/ssGSEA2.0#15]
Hi, I tried to run the package using R version 3.6.1, I managed to load "cmapR" package and changed "parse.gctx" to "parse_gctx" in ssgsea-gui.R and ssGSEA2.0. Every time I try to run ssgsea-gui.R this error message appears:
 
`parsing as GCT v1.3

exprs_GSE13254_ssGSEA-scores.gct 1 rows, 86 cols, 175 row descriptors, 0 col descriptors
Error in dimnames(rdesc) <- list(rid, rhd) : 
  length of 'dimnames' [1] not equal to array extent`

Your advice will be highly appreciated.

**Comment by karstenkrug** [comment]
Please pull the latest version of the repo which does not require the ```cmapR``` package, see below: 

https://github.com/broadinstitute/ssGSEA2.0/issues/14#issuecomment-596668692

Please let me know if this works for you.
K

**Comment by erikfel97** [comment]
Hello,
Thank you for your fast response.
I've pulled the latest version of the repo. As I'm new to R I'm not sure where and how I should specify the .gct file I'm interested to analyze and the specific .gmt file I've created before.
Your advice will be highly appreciated

Best
Erik Feldman
________________________________
מאת: Karsten Krug <notifications@github.com>
‏‏נשלח: יום שני 09 מרץ 2020 19:29
‏‏אל: broadinstitute/ssGSEA2.0 <ssGSEA2.0@noreply.github.com>
עותק: Erik Feldman <erik.feldman@campus.technion.ac.il>; Author <author@noreply.github.com>
‏‏נושא: Re: [broadinstitute/ssGSEA2.0] Constant Error (#15)


Please pull the latest version of the repo which does not require the cmapR package, see below:

#14 (comment)<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbroadinstitute%2FssGSEA2.0%2Fissues%2F14%23issuecomment-596668692&data=02%7C01%7Cerik.feldman%40campus.technion.ac.il%7C1252800e2af74ef850dd08d7c44f78d0%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C637193717921627974&sdata=%2Fq%2BJzI1Jx%2BLcnjWgFFtBKy%2BVKd6DYZEc25EKDp%2FmNvM%3D&reserved=0>

Please let me know if this works for you.
K

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbroadinstitute%2FssGSEA2.0%2Fissues%2F15%3Femail_source%3Dnotifications%26email_token%3DAKCSHJMJPJKS7LFFO2SJET3RGUYRTA5CNFSM4LEHNWL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOIHNWQ%23issuecomment-596670170&data=02%7C01%7Cerik.feldman%40campus.technion.ac.il%7C1252800e2af74ef850dd08d7c44f78d0%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C637193717921637928&sdata=rSeXdMhb2fPSy1zFyZ3LQ%2Fn%2FpyUGd4axJ6sYhYgEKRo%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKCSHJOQE3IX4SB57Y5A553RGUYRTANCNFSM4LEHNWLQ&data=02%7C01%7Cerik.feldman%40campus.technion.ac.il%7C1252800e2af74ef850dd08d7c44f78d0%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C637193717921637928&sdata=1QTcUKoUQVFScaTQQucpH6RTir%2FSJlZufe3LKOXxhwk%3D&reserved=0>.

WARNING: This email is from an external mail server, Please be careful when opening attachments or links.
