### ISSUE TITLE
why different ssGSEA-scores when i run with the same data and parameter?

### ISSUE THREAD

**Issue by lixuenan** [broadinstitute/ssGSEA2.0#18]
when i run ssgsea2.0 with the same data and parameters ,why I got the different score? 
first itme result 
TCGA-E1-A7YJ-01 | TCGA-DH-A66F-01 | TCGA-HT-A614-01 | TCGA-S9-A89Z-01 | TCGA-DU-6397-01
-- | -- | -- | -- | --
0.3471 | 1.3028 | 1.2879 | 1.5655 | 1.6379
second time result
TCGA-E1-A7YJ-01 | TCGA-DH-A66F-01 | TCGA-HT-A614-01 | TCGA-S9-A89Z-01 | TCGA-DU-6397-01
-- | -- | -- | -- | --
0.3408 | 1.2987 | 1.2739 | 1.6126 | 1.6152

I am confused with this result because i want to use median score as cutoff value to group my data , with this differnt score  i get different samples in my group?how can i use my enrichment score?

**Comment by karstenkrug** [comment]
Normalized enrichment scores (NES) and subsequently calculated p-values are based on random permutations of the data vector to estimate a null distribution. That is the reason why the normalized enrichment scores from two runs are not identical. You can try increasing the number permutations to make the scores more robust across multiple runs on the same data but they will never be identical.
Please take a look at the original GSEA publication ([Subramanian et al](https://www.pnas.org/content/102/43/15545)) in which the authors describe the method for the regular GSEA method.
