### ISSUE TITLE
problems with PTM-Signature Enrichment Analysis (PMT-SEA)  by using ssGSEA-gui.R

### ISSUE THREAD

**Issue by wanghao1991217** [broadinstitute/ssGSEA2.0#19]
My GCT file is looks like this:

#1.2 |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
15039 | 50 |   |   |   |   |   |  
id | T_P29 | T_P47 | T_P31 | T_P46 | T_P23 | T_P09 | T_P08
A0A1B0GTH6;S75 | 4.83E+08 | 267440.1 | 4.98E+08 | 87010567 | 267440.1 | 43950071 | 1.49E+08
A0FGR8;S669 | 267440.1 | 267440.1 | 267440.1 | 267440.1 | 267440.1 | 7117097 | 6925523
A0FGR8;S691 | 3877195 | 1.61E+08 | 53212101 | 76584535 | 2.56E+08 | 28505337 | 1.19E+08
A0FGR8;S693 | 18107572 | 29537662 | 802320.4 | 802320.4 | 1.57E+08 | 802320.4 | 93725060
A0FGR8;S699 | 534880.2 | 534880.2 | 3980433 | 32214236 | 534880.2 | 534880.2 | 1.23E+08
A0FGR8;S704 | 534880.2 | 35629607 | 534880.2 | 1.82E+08 | 534880.2 | 534880.2 | 3.48E+08
A0FGR8;S736 | 534880.2 | 41140513 | 534880.2 | 37159060 | 534880.2 | 534880.2 | 534880.2
A0FGR8;S737 | 267440.1 | 12860386 | 87470620 | 36891620 | 267440.1 | 267440.1 | 267440.1
A0FGR8;S738 | 65249605 | 2.47E+08 | 4.77E+08 | 3.69E+08 | 1.48E+08 | 2.74E+08 | 4.67E+08
A0FGR8;S739 | 31605708 | 1.06E+08 | 2.05E+08 | 40219703 | 27271875 | 534880.2 | 45479137
A0FGR8;S755 | 267440.1 | 267440.1 | 1.22E+08 | 267440.1 | 267440.1 | 267440.1 | 267440.1
A0FGR8;S758 | 267440.1 | 46641857 | 40211917 | 267440.1 | 267440.1 | 267440.1 | 267440.1
A0FGR8;S761 | 267440.1 | 267440.1 | 30388404 | 267440.1 | 267440.1 | 267440.1 | 267440.1
A0FGR8;T701 | 17969710 | 1.17E+08 | 9728443 | 2.08E+08 | 802320.4 | 802320.4 | 97671170

And there is no the annotation of directionality in my GCT data. I have noticed that in the documation of PMT-SEA, " the annotation of directionality is a feature of PTMsigDB (column: Example in PTMsigDB) and must not be included when generating compatible site identifier for a particular dataset".  But when I run the ssGSEA-gui with ptm.sig.db.all.uniprot.human.v1.9.0.gmt, there's error that "No overlap to any gene sets found in your data set!".  I checked the data and determined there was overlap.

**Comment by karstenkrug** [comment]
You don't need to annotate directionality in your dataset but please use one of the formats specified in column ```Example in dataset``` of Table 1 in the [Readme](https://github.com/broadinstitute/ssGSEA2.0/blob/master/Readme.md) file. You basically need to add ```-p``` to your site identifiers.
