### ISSUE TITLE
Small test.gct file works fine but whole data.gct gives incorrect number of dimensions error

### ISSUE THREAD

**Issue by qianxu05172019** [broadinstitute/ssGSEA2.0#20]
Hi,

I have one gene count sample and was using the online ssGSEA tool here: https://cloud.genepattern.org/gp/pages/index.jsf?lsid=urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00270:10.0.4

I prepared my own.gct file and tried to do a ssGSEA experiment. When I upload the whole data.gct to the platform and usingc1.all.v7.2.symbols.gmt as geneset files. Using the default settings, it keeps giving an "incorrect number of dimensions" error. But when I extract part of the file by hand as a test.gct file, it just works fine.

I have attached both my count.gct and test.gct here. Can you please help me out? Thanks in advance for any help!

[ssGSEA2.0.zip](https://github.com/broadinstitute/ssGSEA2.0/files/5528131/ssGSEA2.0.zip)

**Comment by karstenkrug** [comment]
Hi,

Please reach out to the devs of the GSEA gene pattern module: https://github.com/GSEA-MSigDB/ssGSEA-gpmodule

Thanks,
K
