### ISSUE TITLE
p values

### ISSUE THREAD

**Issue by storgatan** [broadinstitute/ssGSEA2.0#21]
Hi,
thank you for this nice ssgsea implementation.
I have a question regarding the p values in the output gct file. I noticed that there is no p value below 0.001 and I wondered whether there is a cutoff at 0.001 even if the "real" p values might be even lower. If that should be the case, is there a way to let it calculate the exact p values as well?
Thank you again

**Comment by karstenkrug** [comment]
Thank you! P values are derived from calculating an enrichment score (ES) from random permutations of the data vector (a column in the GCT file) and to compare to the ES calculated form the actual data. The default number of permutations is set to 1000 (parameter "nperm"), thus the smallest p-value one can observe is 1/1000 = 0.001. You could increase the number permutations to get more significant digits in the p-value.
Best,
K
