### ISSUE TITLE
Different distributions in different RNAseq cohorts

### ISSUE THREAD

**Issue by GuillC** [broadinstitute/ssGSEA2.0#26]
Hi,
I'm running the ssGSEA h scores in two different cohorts and for some h scores the distribution is similar in both cohorts, while for some other they are completely different (for instance ranging between 4 and 6 in one cohort and between 7 and 9 in the other).
The RNAseq protocols were different in the two cohorts (one is from 9 years ago and the other recent), is there some normalization I should do ? I was thinking of simply using z-scores.
Thanks !

**Comment by drmani** [comment]
Hello,
I presume you mean H scores from Bhinder & Djaballah, 2012. Either z-scores or ranks should work as input to ssGSEA.

**Comment by GuillC** [comment]
Indeed H scores from Bhinder & Djaballah, 2012
Is it expected that the some scores in two different cohorts are in completely different range ? The observed differences appear way too large to be cohort effects.

**Comment by drmani** [comment]
I do not have any experience with H scores, and therefore cannot answer your question with any authority. Sorry! Maybe inspecting the data that is used to calculate the score may provide some insight?
