### ISSUE TITLE
More input genes, better results?

### ISSUE THREAD

**Issue by LynnChan99** [broadinstitute/ssGSEA2.0#27]
Hi, I am using ssgsea in my recent project recently. However, I am little confused about this probelm: If we input more genes, will we get better infiltration result? 

Looking forward to your reply, and thanks a lot!

**Comment by drmani** [comment]
ssGSEA is designed to be used with all the genes provided as input, ranked based on appropriate criteria. So, the more genes you provide as input, the more robust the results will be -- more genes will increase the overlap with genesets.

**Comment by LynnChan99** [comment]
OK, I see.Thank you for your reply!

---- Replied Message ----
| From | ***@***.***> |
| Date | 11/09/2023 01:10 |
| To | ***@***.***> |
| Cc | LynnChan99 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [broadinstitute/ssGSEA2.0] More input genes, better results? (Issue #27) |

ssGSEA is designed to be used with all the genes provided as input, ranked based on appropriate criteria. So, the more genes you provide as input, the more robust the results will be -- more genes will increase the overlap with genesets.
