### ISSUE TITLE
The exact meaning of "general performance improvements"

### ISSUE THREAD

**Issue by kvittingseerup** [broadinstitute/ssGSEA2.0#4]
In the update description of the ssGSEA function it is mentioned that a set of "general performance improvements" was made. Are these in terms of runtime or in terms of accuracy of results?

**Comment by karstenkrug** [comment]
Good catch! This bullet point refers to runtime improvements, such as replacing for-loops with apply-based functions.  I updated the Readme accordingly.

**Comment by kvittingseerup** [comment]
Thanks for the quick response :)
