### ISSUE TITLE
socket issue

### ISSUE THREAD

**Issue by juechenyang** [broadinstitute/ssGSEA2.0#5]
Hi, 

I am trying to use the command line script "ssgsea-cli.R". However, it always produce the error like 

"Error in socketConnection("localhost", port = port, server = TRUE, blocking = TRUE,  : 
  all connections are in use
Calls: ssGSEA2 ... makePSOCKcluster -> newPSOCKnode -> socketConnection
Execution halted
Error in gzfile(file, "rb") : all connections are in use
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>"

Do you know how to fix it? Thanks so much

**Comment by karstenkrug** [comment]
Hi, can you try to run it with ```-l FALSE```?

**Comment by juechenyang** [comment]
Thanks! it works
