### ISSUE TITLE
Errors about ssGSEA

### ISSUE THREAD

**Issue by realDongWang** [broadinstitute/ssGSEA2.0#7]
when i run "source("ssgsea-gui.R")" and I want to use ssgsea.
There is an error: argument "fname" is missing, with no default

my gmt file looks like this:
S1 No_Data_No_Data AIF1 ALDH2 AMPD3 ANKRD20A12P APOL1 APOL6 
my gct file looks like this:
#1.3
21655   56	0	0
NAME	S1	S2	S3
A1BG	xxx	xxx	xxx

So what is the problem?

**Comment by karstenkrug** [comment]
Could you please try to use the GenePattern module and let me know whether you get the same error there? You have to register to use GenePattern but it's free: https://tinyurl.com/PTM-SEA-GP
