### ISSUE TITLE
bug in combine mode

### ISSUE THREAD

**Issue by yksaito** [broadinstitute/ssGSEA2.0#9]
Hi,
I want to run ssGSEA with "combine.add"  mode.
I modified ssgsea-gui.R to add combine.mode parameter.
```
## run ssGSEA
    gsea.res <- ssGSEA2(input.ds, ...   , combine.mode= "combine.add")
```
But this gives an error.
```
Error in matrix(ol.matrix.2[locs, ], nrow = length(locs)) :
  object 'ol.matrix.2' not found
```
I don't see any error without combine.mode parameter.
I wonder it might be a bug?

**Comment by hd00ljy** [comment]
Hello,

The same error here.

I found out that the ol.matrix.2 is defined before the problematic line
only when the combine mode is off.

In the other cases, ol.matrix.2 is not defined at all

Hope it helps
